swagger: "2.0"
info:
  title: S3 File Listing API
  version: "1.0"
paths:
  /files:
    get:
      summary: List files in S3 bucket
      responses:
        200:
          description: A map of file names to presigned URLs
          schema:
            type: object
            additionalProperties:
              type: string
